name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      run: |
        docker build -t yourdockerhubusername/server:${{ github.sha }} ./server
        docker push yourdockerhubusername/server:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Executing remote SSH commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /path/to/your/project
          git pull
          sed -i 's/image: yourdockerhubusername\/server:.*/image: yourdockerhubusername\/server:${{ github.sha }}/' docker-compose.yml
          docker-compose up -d

    - name: Send notification to Gmail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Deployment Status
        # Customize the body as needed
        body: Deployment of ${{ github.repository }} was successful. Commit SHA: ${{ github.sha }}
        to: your-email@example.com
        from: GitHub Actions <your-sender-email@example.com>
        secure: true
